export const GET_DETECT_LIST_LOADING = 'GET_DETECT_LIST_LOADING';
export const SET_DETECT_LIST = 'SET_DETECT_LIST';
export const DETECT_IMAGE_LOADING = 'DETECT_IMAGE_LOADING';
export const SET_DETECT_DATA = 'SET_DETECT_DATA';
export const CLEAR_RESULT_DATA = 'CLEAR_RESULT_DATA';
